# Generated by Django 4.2 on 2023-05-01 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equacao2Grau',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.DecimalField(decimal_places=4, max_digits=10)),
                ('b', models.DecimalField(decimal_places=4, max_digits=10)),
                ('c', models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
    ]
